plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/mickwilliam/loxleyforest"
publishOrigin = "config"
commandOrigin = "config"
command = "python3 scripts/ensure_gtm.py"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]